print('Bryan')
print("\\")
print("La Witsi Witsi Araña\n subió a su telaraña.")
print("Vino la lluvia\n y se la llevó.")
print("La Witsi Witsi Araña" , "subió" , "a su telaraña.")
print("Mi nombre es", "Python.")
print("Monty Python.")
print("Mi nombre es", "Python.", end=" ")
print("Monty Python.")
print("Mi", "nombre", "es", "Monty", "Python.", sep="-")
print("Mi", "nombre", "es", sep="_", end="*")
print("Monty", "Python.", sep="*", end="*\n")
print("Programming","Essentials","in", sep="***", end="...")
print("Python")
